Jquery is a powerful , lightweight & powerful JS Library.

https://releases.jquery.com/ - CDN

https://www.javatpoint.com/jquery-tutorial 

$ Symbol in Jquery  
https://www.edureka.co/community/183307/what-is-the-meaning-of-symbol-in-jquery#:~:text=%24%20sign%20is%20just%20a%20valid,base%20object%20(or%20function) 

Entire Jquery Learnings
https://hackr.io/blog/how-to-learn-jquery#:~:text=JQuery%20is%20easy%2Dto%2Dlearn,it%20has%204%20basic%20uses 

https://www.geeksforgeeks.org/form-validation-using-jquery/ - Form Validation
